### PR TITLE
[carnet][WIP] Working channel groups / basic polling

### PR DESCRIPTION
**Pull request by fastlorenzo**
1. updated carnet binding to support channel groups
2. added basic polling to retrieve vehicle basic information (Audi)
3. based on openhab-addons master branch for the other bindings

### CODE REVIEW

**Comment by markus7017** [comment]
merged

**Comment by fastlorenzo** [comment]
Great, I was struggling with the sign-off ;)

**Comment by markus7017** [comment]
please move to 2.5.5 build environment

**Comment by fastlorenzo** [comment]
done and pushed to my fork

**Comment by markus7017** [comment]
see PM

**Pull request merged**
