### PR TITLE
Updates to use MyOpenHab.org for proxying events

### PR DESCRIPTION
**Pull request by LoungeFlyZ**
Tweaks and changes to use myopenhab.org to proxy events, updated readme to simplify setup, update to 2.5.6-snapshot.

### CODE REVIEW

**Comment by markus7017** [comment]
first resolve the merge conflicts

**Comment by LoungeFlyZ** [comment]
fixed. sorry not sure what was going on, but hard reset to your branch and remade the changes. hope this works better.

**Comment by markus7017** [comment]
callbackUrl="https://username:password@home.myopenhab.org/rachio/webhook", 

Does that mean I‘m exposing my myopenhab credentials to Rachio (-
as part of the url)?

**Comment by LoungeFlyZ** [comment]
Your myopenhab creds yes. Not the creds of your PC running OpenHab. I created a second username and password in myopenhab.org  for this purpose.

I feel this is much more secure trusting Rachio than exposing my OpenHab API to the internet.

**Comment by markus7017** [comment]
is there no way to request an auth token from myopenhab?

**Comment by LoungeFlyZ** [comment]
not as far as i can see :(  it would be nice to be able to issue tokens in myopenhab.org with certain permissions attached, but it pretty much just acts as a reverse proxy with basic auth strapped on the front of it.

**Pull request merged**
